{
    "name": "Association Membership",
    "version": "18.0.6.3.0",
    "category": "Association",
    "summary": "Multi-company membership management for associations",
    "author": "ECOnGOOD",
    "license": "AGPL-3",
    "post_init_hook": "post_init_hook",
    "depends": [
        "account",
        "contacts",
        "donation_base",
        "mail",
        "product",
    ],
    "data": [
        "security/membership_groups.xml",
        "security/membership_security.xml",
        "security/ir.model.access.csv",
        "data/membership_data.xml",
        "data/membership_templates.xml",
        "data/membership_cron.xml",
        "views/membership_membership_views.xml",
        "views/membership_period_views.xml",
        "views/product_membership_views.xml",
        "views/res_partner_views.xml",
        "views/res_config_settings_views.xml",
        "views/donation_tax_receipt_views.xml",
        "views/membership_activate_wizard_views.xml",
        "views/membership_cancel_wizard_views.xml",
        "views/membership_renewal_wizard_views.xml",
        "report/reporting_actions.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": False,
}
