{
    "name": "Association Membership",
    "version": "18.0.1.0.18",
    "category": "Association",
    "summary": "Lean multi-company membership management for associations",
    "author": "ECOnGOOD",
    "license": "AGPL-3",
    "depends": [
        "account",
        "contacts",
        "mail",
        "product",
    ],
    "data": [
        "security/membership_groups.xml",
        "security/membership_security.xml",
        "security/ir.model.access.csv",
        "data/membership_data.xml",
        "data/membership_cron.xml",
        "views/membership_membership_views.xml",
        "views/membership_contribution_views.xml",
        "views/product_membership_views.xml",
        "views/res_partner_views.xml",
        "views/res_config_settings_views.xml",
        "views/membership_cancel_wizard_views.xml",
        "views/membership_renewal_wizard_views.xml",
        "views/membership_import_wizard_views.xml",
        "report/reporting_actions.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": False,
}
